version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ml-backend
    volumes:
      - ./backend/app/models:/app/models
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: ml-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    container_name: ml-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: